apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-kafka.core.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kafka.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Core.Component }}"
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: broker
    port: {{ .Values.Core.Ports.broker }}
    targetPort: {{ .Values.Core.Ports.broker }}
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kafka.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Core.Component }}"