apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-kafka.zookeeper.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Zookeeper.Labels }}
{{ toYaml .Values.Zookeeper.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kafka.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Zookeeper.Component }}"
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: election
    port: 3888
    protocol: TCP
    targetPort: 3888
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  selector:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Zookeeper.Labels }}
{{ toYaml .Values.Zookeeper.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kafka.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Zookeeper.Component }}"
{{- end }}