{{- if .Values.Manager.Admin.Secret.Create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bdl-kafka.manager.fullname" . }}-credentials-admin
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Manager.Labels }}
{{ toYaml .Values.Manager.Labels | indent 8 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kafka.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Manager.Component }}"
{{- end }}
type: Opaque
data:
  km_user: {{ .Values.Manager.Admin.User | b64enc }}
  km_password: {{ .Values.Manager.Admin.Password | b64enc }}
{{- end }}