apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bdl-presto.fullname" . }}-catalog
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-presto.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Catalog.Component }}"
type: Opaque
data:
{{ range $key, $val := .Values.server.catalog }}
  {{ $key }}: {{ $val | b64enc }}
{{ end }}