{{- if .Values.server.hdfs.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bdl-presto.catalog.fullname" . }}-hive
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-presto.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Catalog.Component }}"
type: Opaque
data:
{{ range $key, $val := .Values.server.hdfs.config }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}