apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bdl-presto.catalog.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Catalog.Labels }}
{{ toYaml .Values.Catalog.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-presto.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Catalog.Component }}"
{{- end }}
type: Opaque
data:
{{ range $key, $val := .Values.server.catalog }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}