# Default values for bdl-spark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

BDL:
  ApiEndpoint: ""

ObjStorage:
  Auth:
    Method: "mock-basic"
    Username: "user-1"
    Password: "pass-1"
  WarehouseDir: ""
  # Auth:
  #   Method: "apikey"
  #   ApiKey: "apikey-1-asdf"
  # Auth:
  #   Method: "apikey"
  #   ApiKey: ""


Master:
  Component: "spark-master"
  Replicas: 1
  Image: "bigstepinc/spark_bdl"
  ImageTag: "2.4.0-1"
  ImagePullPolicy: "IfNotPresent"
  Resources: {}
  DataDir: "/bigstep/data-dir"
  ConfigMapDir: "/bigstep/config"
  Storage: "1Gi"
  StorageClassUseDefault: true
  StorageClass: "-"
  Service:
    Enabled: true
    Type: "LoadBalancer"
  Ports:
    sparkApplicationUI: 4040
    masterWebUI: 8080
    sparkMaster: 7077

  
Worker:
  Component: "spark-worker"
  Replicas: 1
  Image: "bigstepinc/spark_bdl"
  ImageTag: "2.4.0-1"
  ImagePullPolicy: "IfNotPresent"
  Resources: {}
  DataDir: "/bigstep/data-dir"
  Storage: "1Gi"
  StorageClassUseDefault: true
  StorageClass: "-"
  Service:
    Enabled: true
    Type: "LoadBalancer"
  Ports:
    workerWebUI: 8081

Env:
  CORES: "2"
  DRIVER_CORES: "2"
  DRIVER_MEM: "4G"
  EX_CORES: "2"
  EX_MEM: "4G"
  JAVA_DRIVER_OPTS: "Xmx1024M"
  MEM: "4G"

DataBase:
  Enabled: false
  Type: ""
  Hostname: ""
  Port: ""
  CredentialsSecret: ""

Audit:
  Enabled: false
  # MockUserId: ""
  # ESURL: ""
  # ESAuthToken: ""
