# Default values for bdl-spark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



ObjStorage:
  Auth:
    Method: "basic"
    Username: "user-1"
    Password: "pass-1"
  # Auth:
  #   Method: "apikey"
  #   ApiKey: "apikey-1-asdf"

Master:
  Component: "spark-master"
  Replicas: 1
  Image: "bigstepinc/spark_bdl"
  ImageTag: "2.3.0-2"
  ImagePullPolicy: "Always"
  Resources: {}
  DataDir: "/bigstep/data-dir"
  ConfigMapDir: "/bigstep/config"
  Storage: "1Gi"
  StorageClassUseDefault: true
  StorageClass: "-"
  Service:
    Enabled: true
    Type: "LoadBalancer"
  Ports:
    sparkUI: 30002
    masterWebUI: 30003
    sparkMaster: 7077

  
Worker:
  Component: "spark-worker"
  Replicas: 1
  Image: "bigstepinc/spark_bdl"
  ImageTag: "2.3.0-2"
  ImagePullPolicy: "Always"
  Resources: {}
  DataDir: "/bigstep/data-dir"
  Storage: "1Gi"
  StorageClassUseDefault: true
  StorageClass: "-"
  Service:
    Enabled: true
    Type: "LoadBalancer"
  Ports:
    masterWebUI: 8080
    workerWebUI: 30006

Env:
  CORES: "2"
  DRIVER_CORES: "2"
  DRIVER_MEM: "4G"
  EX_CORES: "2"
  EX_MEM: "4G"
  JAVA_DRIVER_OPTS: "Xmx1024M"
  MEM: "4G"

DataBase:
  Enabled: false
  Type: ""
  Hostname: ""
  Port: ""
  CredentialsSecret: ""

Debug:
  Component: "spark-debug"
  ConfigDir: "/bigstep/debug/conf-bdl-scheme"
  Storage: "1Gi"
  StorageClassUseDefault: true
  StorageClass: "-"
