{{ $context := . }}

{{ range $i := until (int .Values.Worker.Replicas) }}
{{ with $context }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "data-{{ template "bdl-spark.worker.fullname" . }}-{{ $i }}"
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Worker.Labels }}
{{ toYaml .Values.Worker.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
{{- end }}
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.Worker.Storage }}"
  {{- if (not .Values.Worker.StorageClassUseDefault) }}
  {{- if (eq "-" .Values.Worker.StorageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.Worker.StorageClass }}"
  {{- end }}
  {{- end }}
{{- if (not (eq $i (int .Values.Worker.Replicas))) }}
---
{{- end }}
{{ end }}
{{ end }}