apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-spark.master.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: spark-application-ui
    port: 4040
    targetPort: 4040
    protocol: TCP
  - name: master-web-ui
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: spark-master
    port: 7077
    targetPort: 7077
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"