apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bdl-spark.master.fullname" . }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
data: