{{ $context := . }}

{{ range $i := until (int .Values.Master.Replicas) }}
{{ with $context }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "data-{{ template "bdl-spark.master.fullname" . }}-{{ $i }}"
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Master.Labels }}
{{ toYaml .Values.Master.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
{{- end }}
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.Master.Storage }}"
  {{- if (not .Values.Master.StorageClassUseDefault) }}
  {{- if (eq "-" .Values.Master.StorageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.Master.StorageClass }}"
  {{- end }}
  {{- end }}
{{- if (not (eq $i (int .Values.Master.Replicas))) }}
---
{{- end }}
{{ end }}
{{ end }}