apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-spark.worker.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Worker.Labels }}
{{ toYaml .Values.Worker.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: worker-web-ui
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Worker.Labels }}
{{ toYaml .Values.Worker.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
{{- end }}