apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-spark.worker.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
spec:
  type: ClusterIP
  ports:
  - name: master-web-ui
    port: {{ .Values.Worker.Ports.masterWebUI }}
    targetPort: {{ .Values.Worker.Ports.masterWebUI }}
    protocol: TCP
  - name: worker-web-ui
    port: {{ .Values.Worker.Ports.workerWebUI }}
    targetPort: {{ .Values.Worker.Ports.workerWebUI }}
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"