apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-postgresql.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: {{ .Values.Ports.postgres.Container }}
    targetPort: {{ .Values.Ports.postgres.Container }}
    protocol: TCP
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
