apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-postgresql.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    heritage: {{ .Release.Service }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}