apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-postgresql.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.Ports.Metastore.Container }}
    targetPort: {{ .Values.Ports.Metastore.Container }}
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"