apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-postgresql.fullname" . }}-clusterip
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"