apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bdl-postgresql.fullname" . }}-credentials-admin
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
type: Opaque
data:
  db_name: {{ .Values.Admin.Name | b64enc }}
  db_user: {{ .Values.Admin.User | b64enc }}
  db_password: {{ .Values.Admin.Password | b64enc }}