{{- if .Values.Service.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-jupyter.fullname" . }}-public
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-jupyter.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
spec:
  type: {{ .Values.Service.Type }}
  {{- if .Values.Service.clusterIP }}
  clusterIP: {{ .Values.Service.clusterIP }}
  {{- end }}
  {{- if .Values.Service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.Service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.Service.loadBalancerIP }}
  {{- end }}
  {{- if eq .Values.Service.Type "LoadBalancer" }}
  {{- if .Values.Service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toJson .Values.Service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
  - name: notebook
    port: {{ .Values.Ports.notebook }}
    targetPort: notebook
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-jupyter.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
{{- end }}