apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-jupyter.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-jupyter.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: notebook
    port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-jupyter.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"