apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "data-{{ template "bdl-jupyter.fullname" . }}"
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-jupyter.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.Storage }}"
  {{- if (not .Values.StorageClassUseDefault) }}
  {{- if (eq "-" .Values.StorageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.StorageClass }}"
  {{- end }}
  {{- end }}