apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-argo.ui.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-argo.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.UI.Component }}"
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: argo-ui
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-argo.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.UI.Component }}"