apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bdl-argo.workflow-controller.fullname" . }}-configmap
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-argo.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.WorkflowController.Component }}"
data:
  config: |
    {{- if .Values.WorkflowController.instanceID.enabled }}
    {{- if .Values.WorkflowController.instanceID.useReleaseName }}
    instanceID: {{ .Release.Name }}
    {{- else }}
    instanceID: {{ .Values.WorkflowController.instanceID.explicitID }}
    {{- end }}
    {{- end }}
