{{- if .Values.WorkflowController.ServiceAccount.Create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "bdl-argo.workflow-controller.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "bdl-argo.workflow-controller.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: "{{ template "bdl-argo.workflow-controller.fullname" . }}-{{ .Values.WorkflowController.ServiceAccount.NameBase }}"
    namespace: {{ .Release.Namespace }}
{{- if .Values.WorkflowController.workflowNamespaces }}
{{- $namespace := .Release.Namespace }}
{{- range $key := .Values.WorkflowController.workflowNamespaces }}
  {{- if not (eq $key $namespace) }}
  - kind: ServiceAccount
    name: "{{ template "bdl-argo.workflow-controller.fullname" . }}-{{ .Values.WorkflowController.ServiceAccount.NameBase }}"
    namespace: {{ $key }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}