apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "bdl-postgresql.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-postgresql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  serviceName: "{{ template "bdl-postgresql.fullname" . }}"
  replicas: {{ default 1 .Values.Replicas }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Component }}"
  template:
    metadata:
      name: "{{ template "bdl-postgresql.fullname" . }}"
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "bdl-postgresql.chart" . }}
        component: "{{ .Release.Name }}-{{ .Values.Component }}"
    spec:
      containers:
      - name: "{{ template "bdl-postgresql.fullname" . }}"
        image: "{{ .Values.Image }}:{{ .Values.ImageTag }}"
        imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
        ports:
        - name: metastore
          containerPort: {{ .Values.Ports.Metastore.Container }}
          protocol: TCP
        resources:
{{ toYaml .Values.Resources | indent 10 }}
        env:
        - name: CONTAINER_DIR
          value: {{ .Values.DataDir }}/postgres
################################################
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ template "bdl-postgresql.fullname" . }}-credentials-admin
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "bdl-postgresql.fullname" . }}-credentials-admin
              key: db_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "bdl-postgresql.fullname" . }}-credentials-admin
              key: db_password

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "bdl-postgresql.fullname" . }}-credentials-project
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "bdl-postgresql.fullname" . }}-credentials-project
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "bdl-postgresql.fullname" . }}-credentials-project
              key: db_password
################################################
        - name: POSTGRES_HOSTNAME
          value: "{{ template "bdl-postgresql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "{{ .Values.Ports.Metastore.Container }}"
        volumeMounts:
        - name: datadir
          mountPath: {{ .Values.DataDir }}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ template "bdl-postgresql.fullname" . }}
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 10