{{- if .Values.Service.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-sftp-proxy.fullname" . }}-public
  labels:
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sftp-proxy.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
spec:
  type: {{ .Values.Service.Type }}
  {{- if .Values.Service.clusterIP }}
  clusterIP: {{ .Values.Service.clusterIP }}
  {{- end }}
  {{- if .Values.Service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.Service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.Service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.Service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toJson .Values.Service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  ports:
  - name: ssh-server
    port: {{ .Values.Ports.sshserver }}
    targetPort: 22
    protocol: TCP
  selector:
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sftp-proxy.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
{{- end }}
