{{ $context := . }}

{{ range $i := untilStep 0 1 2 }}
{{with $context}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name: "{{ template "bdl-spark.worker.fullname" . }}-data"
  name: "data-{{ template "bdl-spark.worker.fullname" . }}-{{ $i }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.Worker.Storage }}"
  {{- if (not .Values.Worker.StorageClassUseDefault) }}
  {{- if (eq "-" .Values.Worker.StorageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.Worker.StorageClass }}"
  {{- end }}
  {{- end }}
  {{end}}
{{ end }}