{{- if .Values.Master.Service.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-spark.master.fullname" . }}-public
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  type: {{ .Values.Master.Service.Type }}
  {{- if .Values.Master.Service.clusterIP }}
  clusterIP: {{ .Values.Master.Service.clusterIP }}
  {{- end }}
  {{- if .Values.Master.Service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.Master.Service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.Master.Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.Master.Service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.Master.Service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.Master.Service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  ports:
  - name: spark-app-ui
    port: {{ .Values.Master.Ports.sparkAppUI }}
    targetPort: 4040
    protocol: TCP
  - name: master-web-ui
    port: {{ .Values.Master.Ports.masterWebUI }}
    targetPort: 8080
    protocol: TCP
  - name: spark-master
    port: {{ .Values.Master.Ports.sparkMaster }}
    targetPort: 7077
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-spark.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
{{- end }}