apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "bdl-kaniko.fullname" . }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kaniko.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  template:
    spec:
      containers:
      - name: "{{ template "bdl-kaniko.fullname" . }}"
        image: "{{ .Values.kaniko.Image }}"
        imagePullPolicy: "{{ .Values.kaniko.ImagePullPolicy }}"
        resources:
{{ toYaml .Values.Resources | indent 10 }}
        args: [ "--build-arg", "PIP_PACKAGES={{ .Values.PipPackages }}",
                "--build-arg", "OS_PACKAGES={{ .Values.OsPackages }}",
                "--build-arg", "NOTEBOOK_NAME=notebook.ipynb",
                "--dockerfile=Dockerfile",
                "--context=/context",
                "--destination={{ .Values.kaniko.Destination }}:{{ .Values.kaniko.Tag }}",
                "--single-snapshot" ]
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker
          - name: context
            mountPath: /context
          - name: bash-config
            mountPath: /root/envs
          - name: config
            mountPath: /context/notebook
      initContainers:
      - name: "{{ template "bdl-kaniko.fullname" . }}-sync"
        image: "{{ .Values.sync.Image }}"
        imagePullPolicy: "{{ .Values.sync.ImagePullPolicy }}"
        env:
          - name: SOURCE_REPO
            value: "{{ .Values.sync.Repository }}"
        volumeMounts:
          - name: context
            mountPath: /context
      restartPolicy: Never
      volumes:
        - name: docker-config
          projected:
            sources:
            - secret:
                name: "{{ template "bdl-kaniko.fullname" . }}-docker-config"
                items:
                - key: .dockerconfigjson
                  path: config.json
        - name: context
          emptyDir: {}
        - name: config
          configMap:
            name: "{{ template "bdl-kaniko.fullname" . }}"
        - name: bash-config
          configMap:
            name: "{{ template "bdl-kaniko.fullname" . }}-bash"