apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "bdl-kaniko.fullname" . }}-docker-config"
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kaniko.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "bdl-kaniko.imagePullSecret" . }}