apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-kaniko.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "bdl-kaniko.imagePullSecret" . }}