{{- if .Values.Admin.Secret.Create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bdl-streamsets.fullname" . }}-credentials-admin
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-streamsets.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
type: Opaque
data:
  ss_password: {{ .Values.Admin.Password | b64enc }}
{{- end }}