{{- if .Values.Service.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-hive.fullname" . }}-public
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-hive.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  type: {{ .Values.Service.Type }}
  {{- if .Values.Service.clusterIP }}
  clusterIP: {{ .Values.Service.clusterIP }}
  {{- end }}
  {{- if .Values.Service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.Service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.Service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.Service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toJson .Values.Service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.Ports.hive }}
      targetPort: 9083
      protocol: TCP
      name: hive
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-presto.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}