apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-hive.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-hive.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: hive
    port: 9083
    targetPort: 9083
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-hive.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}