{{- if .Values.Master.Service.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-sparksql.master.fullname" . }}-public
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Master.Labels }}
{{ toYaml .Values.Master.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sparksql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
{{- end }}
spec:
  type: {{ .Values.Master.Service.Type }}
  {{- if .Values.Master.Service.clusterIP }}
  clusterIP: {{ .Values.Master.Service.clusterIP }}
  {{- end }}
  {{- if .Values.Master.Service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.Master.Service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.Master.Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.Master.Service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.Master.Service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toJson .Values.Master.Service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  ports:
  - name: ui-proxy
    port: {{ .Values.Master.UIProxy.Ports.masterWebUIProxy }}
    targetPort: 80
    protocol: TCP
  - name: spark-app-ui
    port: {{ .Values.Master.Ports.sparkAppUI }}
    targetPort: 4040
    protocol: TCP
  - name: spark-master
    port: {{ .Values.Master.Ports.sparkMaster }}
    targetPort: 7077
    protocol: TCP
  - name: thrift
    port: {{ .Values.Master.Ports.thrift }}
    targetPort: 10000
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Master.Labels }}
{{ toYaml .Values.Master.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sparksql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
{{- end }}
{{- end }}
