apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-sparksql.master.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sparksql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  type: ClusterIP
  clusterIp: None
  sessionAffinity: None
  ports:
  - name: spark-ui
    port: {{ .Values.Master.Ports.sparkUI }}
    targetPort: {{ .Values.Master.Ports.sparkUI }}
    protocol: TCP
  - name: master-web-ui
    port: {{ .Values.Master.Ports.masterWebUI }}
    targetPort: {{ .Values.Master.Ports.masterWebUI }}
    protocol: TCP
  - name: spark-master
    port: {{ .Values.Master.Ports.sparkMaster }}
    targetPort: {{ .Values.Master.Ports.sparkMaster }}
    protocol: TCP
  - name: jupyter-ui
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: thrift-port
    port: 10000
    targetPort: 10000
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sparksql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"