{{- if .Values.Worker.Service.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-sparksql.worker.fullname" . }}-public
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Worker.Labels }}
{{ toYaml .Values.Worker.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sparksql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
{{- end }}
spec:
  type: {{ .Values.Worker.Service.Type }}
  {{- if .Values.Worker.Service.clusterIP }}
  clusterIP: {{ .Values.Worker.Service.clusterIP }}
  {{- end }}
  {{- if .Values.Worker.Service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.Worker.Service.externalIPs | indent 4 }}
  {{- end }}
  {{- if .Values.Worker.Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.Worker.Service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.Worker.Service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toJson .Values.Worker.Service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  ports:
  - name: worker-web-ui
    port: {{ .Values.Worker.Ports.workerWebUI }}
    targetPort: 8081
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Worker.Labels }}
{{ toYaml .Values.Worker.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-sparksql.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Worker.Component }}"
{{- end }}
{{- end }}
