apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdl-mleap.fullname" . }}-internal
  labels:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-mleap.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
  - name: mleap
    port: {{ .Values.Ports.mleap }}
    targetPort: 65327
    protocol: TCP
  selector:
    heritage: {{ .Release.Service | quote }}
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-mleap.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
