apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bdl-mleap.fullname" . }}
  labels:
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 4 }}
{{- else }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-mleap.chart" .}}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
  heritage: {{ .Release.Service | quote }}
spec:
  serviceName: "{{ template "bdl-mleap.fullname" . }}"
  replicas: {{ .Values.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 6 }}
{{- else }}
      release: {{ .Release.Name | quote }}
      chart: {{ template "bdl-mleap.chart" .}}
      component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
    heritage: {{ .Release.Service | quote }}
  template:
    metadata:
      labels:
{{- if .Values.Labels }}
{{ toYaml .Values.Labels | indent 8 }}
{{- else }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "bdl-mleap.chart" .}}
        component: "{{ .Release.Name }}-{{ .Values.Component }}"
{{- end }}
      heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - name: "{{ template "bdl-mleap.fullname" . }}"
        image: "{{ .Values.Image }}:{{ .Values.ImageTag }}"
        imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
        terminationMessagePolicy: "File"
        terminationMessagePath: "/dev/termination-log"
        readinessProbe:
          exec:
            command:
            - /readyness_probe.sh
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 10
        ports: 
        - name: mleap
          containerPort: 65327
          protocol: TCP
        resources:
{{ toYaml .Values.Resources | indent 10 }}
        env:
        - name: DATALAKE_ID
          value: "{{ .Values.BDL.DatalakeId }}"
        - name: PROJECT
          value: "{{ .Values.BDL.ProjectName }}"
        - name: AUTH_METHOD
          value: "{{ .Values.ObjStorage.Auth.Method }}"
        {{- if (eq .Values.ObjStorage.Auth.Method "apikey") }}
        - name: AUTH_APIKEY
          value: "{{ .Values.ObjStorage.Auth.ApiKey }}"
        - name: API_ENDPOINT
          value: "{{ .Values.BDL.ApiEndpoint }}"
        {{- end }}
        - name: BDL_DEFAULT_PATH
          value: "{{ .Values.ObjStorage.BdlDefaultPath }}"
        - name: MODEL_BDL_PATH
          value: "{{ .Values.ModelPath }}"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedularName: default-scheduler
    revisionHistoryLimit: 10
