apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bdl-presto.coordinator.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "bdl-presto.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Coordinator.Component }}"
spec:
  serviceName: "{{ template "bdl-presto.coordinator.fullname" . }}"
  replicas: {{ .Values.Coordinator.Replicas }}
  selector:
    matchLabels:
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      chart: {{ template "bdl-presto.chart" . }}
      component: "{{ .Release.Name }}-{{ .Values.Coordinator.Component }}"
  template:
    metadata:
      annotations:
        checksum/presto-catalog-secret: {{ include (print $.Template.BasePath "/presto-catalog-secret.yaml") . | sha256sum }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "bdl-presto.chart" . }}
        component: "{{ .Release.Name }}-{{ .Values.Coordinator.Component }}"
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "bdl-presto.coordinator.fullname" . }}
        - name: catalog-volume
          secret:
            secretName: {{ template "bdl-presto.catalog.fullname" . }}
        - name: hive-volume
          secret:
            secretName: {{ template "bdl-presto.catalog.fullname" .}}-hive
      containers:
      - name: {{ .Chart.Name }}-coordinator
        image: "{{ .Values.Coordinator.Image }}:{{ .Values.Coordinator.ImageTag }}"
        imagePullPolicy: {{ .Values.Coordinator.ImagePullPolicy }}
        # command: ["/bin/bash"]
        # args:
        #   - {{ .Values.server.config.path }}/docker-presto.sh
        volumeMounts:
          - mountPath: {{ .Values.server.config.path }}
            name: config-volume
          - mountPath: {{ .Values.server.config.path }}/catalog
            name: catalog-volume
          - mountPath: {{ .Values.server.config.path}}/hive
            name: hive-volume
        ports:
          - name: http-coord
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /v1/cluster
            port: http-coord
        readinessProbe:
          httpGet:
            path: /v1/cluster
            port: http-coord
        resources:
{{ toYaml .Values.Coordinator.Resources | indent 10 }}